### ISSUE TITLE
ADA Makerspace Hackathon - Planning Meeting - 31st July 2021

### ISSUE THREAD

**Issue by Sapereaude7** [Catalyst-Swarm/Catalyst-Beehive#101]
## ADA Makerspace Hackathon  - Planning Meeting - - 31st July 2021
https://adamaker.space/open-source-experiential-learning%e2%80%8b/
- [ ] Next steps for Swarm
- [ ] Coordination (internal)
- [ ] Talking about goals etc.
- [ ] Delegating responsibilities

## Tasks
- [ ] Prepare Hackathon Discord Server  - @whitevo 
- [ ] Hackathon  - Mini-proposal workshops - @whitevo 
- [ ] Know how to navigate Boone's virtual environment - @whitevo 
- [ ] Pipeline document ready by next week - 10th August 2021 - @Sapereaude7 
- [ ] Involvement of Catalyst School in Hackathon   - @victorcorcino , @Seomon4u 
- [ ] Consulting / Mentorship role - Robert

### Workshop Facilitators
- Mini-proposal workshops - Tevo

### Event Organizers
- Create Hackathon Discord Server 
- Have some idea about strategy and event detail - Boone, Felix, Jacob

###  Communicators
- Townhall?
- Swarm Discord
- Telegram
- Reddit - https://www.reddit.com/r/cardano/
- Twitter - https://twitter.com/CatalystSwarm / https://twitter.com/qa_dao
- Podcasts - Keww?
- IOG Channel - Daniel

### 26th July 2021
 - User Registration
### 11th August 2021 - Townhall Pitch
- Townhall Q & A
- Idea Interactions

### 13th August 2021 - Opening
- Event Timeline Explanation
- Meet and Greet room
- Aug 13th, 2021 – Event Kick 
- 17:00-18:00 UTC | Occam Challenges & AMA with Elliot Hill in Zoom
- 18:00-19:00 UTC | Adosia Challenges & AMA with Kyle Solomon in Zoom
- 20:00-21:00 UTC | Open Space AMAs with Startup Ideas in Virtual Event Space
- 22:00-23:00 UTC | Open Space AMAs with Web & Biz DEVs in Virtual Event Space
- You can use the Virtual Event Space anytime during August 13th-29th to meetup with others.

### 14th August 2021 - - Swarm Session
- Interaction between voters & proposers
- Workshops

### 15th August 2021
- Aug 15th, 2021 – AMA Event
- To Be Announced Github Thought Leader AMA in Zoom
- 13:00-14:00 UTC | Open Space AMAs with Startup Ideas in Virtual Event Space
- 14:00-15:00 UTC | Open Space AMAs with DEVs in Virtual Event Space
- 20:00-21:00 UTC | Open Space AMAs with Startup Ideas in Virtual Event Space
- 22:00-23:00 UTC | Open Space AMAs with DEVs in Virtual Event Space

### 18th to 21st August 2021
- Interim Onboarding and Feedback

### Aug 22nd, 2021 – Idea Milestone Event
- To Be Announced Github Thought Leader AMA in Zoom
- 13:00-14:00 UTC | Open Space AMAs with Startup Ideas in Virtual Event Space
- 14:00-15:00 UTC | Open Space AMAs with DEVs in Virtual Event Space
- 20:00-21:00 UTC | Open Space AMAs with Startup Ideas in Virtual Event Space
- 22:00-23:00 UTC | Open Space AMAs with DEVs in Virtual Event Space

### Aug 27th, 2021 – Idea Milestone Event 
 - To Be Announced Github Thought Leader AMA in Zoom
- 12:00-13:00 UTC | Three Minute Progress Pitches from Startup Ideas in Zoom
- 13:00-14:00 UTC | Open Space AMAs with Startup Ideas in Virtual Event Space
- 14:00-15:00 UTC | Open Space AMAs with DEVs in Virtual Event Space
- 20:00-21:00 UTC | Open Space AMAs with Startup Ideas in Virtual Event Space
- 22:00-23:00 UTC | Open Space AMAs with DEVs in Virtual Event Space
- 24:00-23:00 UTC | Three Minute Progress Pitches from Startup Ideas in Zoom

### 28th August 2021
- Weekly Reporting of progress

### 29th August 2021 - Final Presentation - Winners Party
- 17:00-18:30 UTC | Occam Occelerator Intro & AMA with Elliot Hill in Zoom
- 18:30-19:00 UTC | Challenge Winners Announced 
- 19:00-19:30 UTC | Top 3 Startup Idea Winners Announced
- 19:30-24:00 UTC | Open Space Celebration in Virtual Event Space

### 1) Hackathon Pitch
> Answer these Questions in your Pitch
> If you had a Minimal Viable Product (NVP) how would people use it?
>What actions do you think people are going to take with your MVP?
>What do you need to prove about your potential customers?
>Please pitch a startup …

### 2) Hackathon Start-up Ideas
> ADA MakerSpaceHackathon Startup Ideas Attendee Pitches Read and Comment on startup ideas pitched by people taking part in hackathon.
> If you are interested in the idea as a potential customer/user of the idea, please give your feedback. If you are …

### 3) Hackathon Challenges

![2021-07-31 (1)](https://user-images.githubusercontent.com/25156451/127735008-e6a7eb06-b618-44c6-a5d0-b0945e8c1249.png)

## Workshops

- Mini-Proposal (problem sensing)
- Haskell Lectures?
- Stakepool operations?
-

**Comment by Sapereaude7** [comment]
Here is a miro-board Tevo created: 
https://miro.com/app/board/o9J_l4JOKnM=/

**Comment by stephen-rowan** [comment]
![2021-07-31](https://user-images.githubusercontent.com/25156451/127734917-b7a6e8e7-dc93-4922-b76c-6545f8c76ee4.png)
