### ISSUE TITLE
Core-Swarm-Meeting - 2nd August 2021 - 17:00 - 18:15 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#102]
## Core-Swarm-Meeting - 2nd August 2021 - 17:00 - 18:15 UTC
- Last Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/96
- Next Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/105

### Moderator
- [x] JakobD

### Attendees
Checked Names confirmed as Attendees.

- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [x] Tevo 
- [x] Victor Corcini
- [x] Seomon 

### Documentation
- [x] @stephen-rowan

## Agenda Items
- [x]  Introduction - How is everybody doing?
- [x]  Expenses Update - Everybody should pay again
- [x]  Coordination with Boone - Update Makerspace Hackathon
- We created a first draft and timeline 
- ADA Makerspace Hackathon - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/101
- We need to address marketing - Victor / Jacob
- The idea of running mini-proposals - was added to the Hackathon - after Hackathon advice - fed from mini-proposal workshop  - Tevo
- Robert O'Brien can provide mentor-ship and advice - Felix / Stephen
- [x]  ATH Preparation this week - After Town Hall - 4th August 2021 - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/104
- Phil is presenting the lovebomb at TownHall
- Keep Catalyst Circle this week - Victor
- Keep Mini-Proposal - new iteration - Tevo
### Breakout Rooms
- | Sala de Cafe "Guía de Project Catalyst"
- Mini Proposal Workshop | Tevo Saks | Stephen
- Cardano blockchain technical usecases - Filip | Jakob | 
- Seomon | Aftergame
- Aidan? | Gaming?

![2021-08-02 (15)](https://user-images.githubusercontent.com/25156451/127906640-6cd47e2d-8944-47f6-9c50-6cb463aa429f.png)

- [x] Roles and Responsibilities -  https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/46
 - See  -https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/78
 - Victor - to help organizing and announcing meetings
- [x]  Proposal Update? - Draft Swarm Fund 6 Proposals  - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/80 - proposal draft update @dominiktilman and @FilipBl4gojevic
- There will be an update in Core Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/105 - Dominic / Filip
- [x] Distributing the 20k
- Will prepare possible breakdown of funding distribution in Core Meeting - Friday 6th August 2021 - Dominic 
- [x] Setting up Website
- Need to update website to reflect who Swarm is, what we do - etc - Jacob
- We need to link to the website to supplement information on our Fund 6 proposals - Dominic
- Website Meeting - Thursday 5th August -  8 UTC
- [x]  Social Media
- Arrange meeting to advance Social Media strategy - Jacob, Dominic, Stephen

##  Any Other Business
- August is usually a very quiet month - Filip
- I do not think August will be so quiet - because Fund 6 and ADA market warming up - Victor
- Talk to IOG re consulting - Felix
- Estonia consulting - in 2 months a vocational course offer funds for startup - also assists in Business Plan drafts - Tevo
- Emurgo Developer programme - use cases - transaction model - metadata - live programming -may bring some vocational / practical outcomes - Filip 
- Tracking participation numbers for attendence is Hosts responsibility - Dominic
- Track Breakout rooms - which rooms are more popular than others - Simon

## List of Open Agenda Items
List of Open Agenda Items - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues?q=is%3Aissue+is%3Aopen+label%3A%22Agenda+Item%22

**Comment by FilipBl4gojevic** [comment]
- proposal draft update @dominiktilman and @FilipBl4gojevic

**Comment by stephen-rowan** [comment]
> 
> 
>     * proposal draft update @dominiktilman and @FilipBl4gojevic

Added to Agenda in main body of this Issue

**Comment by Sapereaude7** [comment]
Introduction - How is everybody doing?
Expenses Update - Everybody should pay again
Coordination with Boone - Update Makerspace Hackathon
ATH Preparation this week
Proposal Update?
Distributing the 20k
Setting up Website
Social Media

**Comment by stephen-rowan** [comment]
> 
> 
> Introduction - How is everybody doing?
> Expenses Update - Everybody should pay again
> Coordination with Boone - Update Makerspace Hackathon
> ATH Preparation this week
> Proposal Update?
> Distributing the 20k
> Setting up Website
> Social Media

Added Agenda to main body
