### ISSUE TITLE
Core Swarm Activities - Friday, 9th July 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#12]
# Tasks to complete for Friday, 9th July 2021
Swarm members can be mentioned (e.g. @stephen-rowan ) here to alert them to these tasks. You can also set up email alerts for mentions.

# Today's Contributors 

## Idea Fest Preparation / IOG

- DominikTilman
- FelixWeber
- Filip
- Seo4u
- Victor Corcin
- @whitevo

## Documentation
@stephen-rowan

**Comment by stephen-rowan** [comment]
An example comment

**Comment by stephen-rowan** [comment]
## Tracking Core Swarm Decision-Making and Documentation.

As an interim solution I suggest I start tracking Core Swarms decisions, discussions, and preparation as daily issues. I can link to other tools from the GitHub Issue (so Core Swarm are not required to use GitHub). But the Catalyst community will have full access to Swarm's daily activities via a simple web link. 
As for documents stored on the Google Drive – it would be good if their status is marked (e.g. Draft, Compete, Private). So I can then migrate the completed material to the GitHub documents repository.

**Comment by stephen-rowan** [comment]
# A Generic Friday Checklist Design

## Swarm Circles and hosts 
- [ ] Confirm Swarm Circles and hosts 

## Announce Session in Swarm Discord
- [ ] Announce Session in Swarm Discord
Link to Discord Announcements channel ( https://discordapp.com/channels/832894680290951179/836129396778991616/836129648671850537)
- [ ] Announce Session in Cardano Project Catalyst Discord (https://discord.gg/2vxtNTvJfZ)

## Update Session Miro Board
- [ ] Update Session Miro Board - @whitevo 
Link to  Miro Board

## Update Website
- [ ] Update Website
https://www.swarm4catalyst.com/
