### ISSUE TITLE
Core Swarm Activities - Wednesday, 7th July, 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#13]
## Tasks to complete for Wednesday, 7th July, 2021
Swarm members can be mentioned (e.g. @stephen-rowan ) here to alert them to these tasks. You can also setup email alerts for mentions.

## Preparation 
- DominikTilman
- FelixWeber
- Filip
- Seo4u
- Victor Corcin
- @whitevo 

## Documentation
@stephen-rowan 

### Telegram link

https://t.me/cardanocatalyst/283

Presentations from the community
👉 Updates regarding Fund4 results and funding/rewards
👉 Road ahead for Fund5 voter registrations
👉 Preview of the Catalyst Idea Fest happening this Saturday

## Miro Board

https://miro.com/app/board/o9J_l77G8AE=/

### After Town hall breakout rooms: 

- Idea Fest. 
Hosts: Filip Blagojevic & Tevo Saks

- ADA Makerspace Hackathon. 
Host : Boone Bergsma

- Catalyst Circle discussions 
Hosts: Victor Corcino, Lauris Stiglics, Felix Weber

- Catalyst School
Hosts: Simon & Stefan Montalbetti

- Inclusion and diversity 
Host: Kerstin Nobel & Nori Nishigaya

- Sala de Cafe “Guia de Project Catalyst” ( Spanish language based )
Host: Ayax Labombarda

### After Town Hall (ATH) Checklist

- [x] Upfront Menu for ATH

- [x] Feedback for ATH

- [x]  Tracking on ATH registrations and participations

**Comment by stephen-rowan** [comment]
## Idea Fest ATH

Miro Transcription ( https://miro.com/app/board/o9J_l77G8AE=/ ) 

### What is the best outcome we can expect ?
- Raise the bar of understanding the proposals.
- Meet the people behind the proposal
- Outreach and opportunity to get word out.
- As a host I expect to stay in time
- Facilitate making an educated decision about a proposal.

### Lot of videos going to recorded, what is done with them and how are they presented ?

- Thinking about Splitting up all the records.
- Videos can be added to the voter-tool.
