### ISSUE TITLE
Action Item - Create a checklist for ATH and Swarm session

### ISSUE THREAD

**Issue by whitevo** [Catalyst-Swarm/Catalyst-Beehive#42]
# Action Item - Create a checklist for ATH and Swarm session

Caused a bit of mess without the speaker not having a co-host when everyone left to breakout rooms

# Moderator Checklist for sessions

- [ ] Give co-host access to all the facilitators.
- [ ] Describe what is this event about
- [ ] Explain the process how event will be carried through
- [ ] Give voice to facilitators to allow them invite people to their room
- [ ] Suggest using collective Miro Board

# Host Checklist for sessions

- [ ] The host or co-host should assert the main subject over anyone who misdirects the session.
- [ ] This will help to keep the discussion and get the expected results
- [ ] Before each session a host should have prepared some content or know what they intend to present.
- [ ] Some preparation always helps
- [ ] When the session starts the host should ask if the attendees mind being recorded.
- [ ] This will help us to find out if we can upload the video to the Swarm session Youtube channel.
- [ ] The host should record the session (if there are no objections).
- [ ] To create asymmetric content

**Comment by stephen-rowan** [comment]
Please update checklist documentation here ( https://catalyst-swarm.gitbook.io/catalyst-swarm-genesis/governance/after-town-halls#checklist )  and here (https://catalyst-swarm.gitbook.io/catalyst-swarm-genesis/governance/saturday-swarm-sessions#checklist )

**Comment by stephen-rowan** [comment]
See this Feedback on ATH 21st July 2021 here : https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/49#issuecomment-884813724

Updated checklist documentation here ( https://catalyst-swarm.gitbook.io/catalyst-swarm-genesis/governance/after-town-halls#checklist )

**Comment by stephen-rowan** [comment]
Added this checklist to https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/72

### Checklist Documented [here](https://catalyst-swarm.gitbook.io/catalyst-swarm-genesis/governance/saturday-swarm-sessions#checklist) 

- [ ] suggest changes to @stephen-rowan 
- [ ] The host or co-host should assert the main subject over anyone who misdirects the session.
- [ ] Before each session a host should have prepared some content or know what they intend to present.
- [ ] When the session starts the host should ask if the attendees mind being recorded.
- [ ] The host should record the session (if there are no objections).
- [ ] The host should end the recording after the session times out (45 minutes).
- [ ] The host or co-host should take notes of the session.

**Comment by stephen-rowan** [comment]
Related to this Issue - Checklist for After Town Hall Preparation #73

**Comment by stephen-rowan** [comment]
Related to this Issue - Enable automatic co-host for core team #50

**Comment by whitevo** [comment]
https://docs.google.com/document/d/1u-ONmUfpIzVOWctlsMKkR1-ATVeDqIcZx98dvteCRvU/edit

**Comment by whitevo** [comment]
Idk, should we need anything else for this action item or we can close it?

**Comment by stephen-rowan** [comment]
Added the text of your checklist to the main body of this issue and to documentation here ( https://catalyst-swarm.gitbook.io/catalyst-swarm-genesis/governance/after-town-halls#checklist)  and here (https://catalyst-swarm.gitbook.io/catalyst-swarm-genesis/governance/saturday-swarm-sessions#checklist) .

I changed "To create asymmetric content" to  "The host or co-host should take notes of the session." in the documentation. I will add the checklist to every ATH and Swarm Issue. And close it here.
