### ISSUE TITLE
Core Swarm Meeting - 23rd July 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#71]
### Attendees
Checked Names confirmed as Attendees.

- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [x] JakobD
- [x] Tevo 
- [ ] Victor Corcini
- [x] Seomon 

### Documentation

- [x] @stephen-rowan

## Agenda Items
- Open Agenda Items can be filtered using this link
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues?q=is%3Aissue+is%3Aopen+label%3A%22Agenda+Item%22

- [ ] Mood-Check

Discussion of commitment from Core Swarm going forward. Jacob committed to Moderating ATH. 
Filip committed to the financial aspect and tokenomics. Fund 6 proposal development with dominiktilman 
More synergy between ATH and Saturday Swarm Sessions ? Jacob
Too much quantity not enough quality ?
Changing the timetables of ATH and Saturday Swarm ?
Follow a preparation checklist.
Each week experiment with new things each week, Reach out to new people - Felix
Now we are much more limited in resources - so experiment is less possible - Filip.
Each of us should focus on bring new people in. How we can evolve our current formats - Jacob
We need to return to the central issue of commitment - Felix
What we can contribute in terms of my own time I think is a sufficient commitment  - dominiktilman 
What activities are and are not Swarm - dominiktilman 

- [ ] Distribution of edited clips regarding idea fest

Send email to all Idea Fest participants informing them of the situation regarding edited clips. @dominiktilman 

- [ ] Communication & partnership with SPOCRA

Monthly meeting between core teams of SPOCRA and Swarm. Liaise with Ron 

- [ ] Set up ADA Makerspace Hackathon #52 - 

Felix chatting with Boone and Dany whether we can have an August TH to present Hackathon 
Maybe we can do a collective brainstorm on how to participate in Hackathon - Jacob
OccamFi already have some challenges that participants can pursue - Ron

- [ ] Github - Emerging questions
Jacob to raise Agenda Items as Issues - Jacob and @stephen-rowan to assist
Anyone in core Swarm can raise an Agenda Item - but Jacob will moderate all Agenda Items.

Why Weekly tasks 

- [ ] Planning for Saturday Swarm Session - 24th July 2021 (https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/72 ) 
- [ ] ATH Feedback + Tracking

## Any Other Business
- [ ] Peter from AdaTruth to attend Monday Meeting on to explain feedback on the timeliness of editing clips
- [ ] Schedule 30 minutes to discuss Idea Fest Feedback - 16:30 UTC
- [ ] Swarm Fund 6 Proposals (or on Monday)
- [ ] Enspiral: Contact to Malcolm Colman-Shearer - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/44
- [ ] Simon and Tevo to discuss Swarm File Structure
- [ ] Chase Swarm Account for Miro - Felix

**Comment by Sapereaude7** [comment]
Agenda for today:
Mood-Check
Distribution of edited clips regarding idea fest
communication & partnership with SPOCRA
Enspiral: Contact to Malcolm Colman-Shearer
Github - Emerging questions
Swarm Session Tomorrow
ATH Feedback + Tracking 
Swarm Fund 6 Proposals (or on Monday)

**Comment by stephen-rowan** [comment]
Thanks Jacob - I have moved Agenda Items to the body of this Issue.

**Comment by Sapereaude7** [comment]
Hey Stephen thank you for updating the Agenda! Could you mabye remove Enspiral and put in the Hackathon instead?
