### ISSUE TITLE
Saturday Swarm Session - 24th July 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#72]
# Saturday Swarm Session - 24th July 2021

## Tasks

- [x] Aidan to moderate
- [x] Website updated to include this Saturday's Sessions - https://www.swarm4catalyst.com/ @whitevo 
- [x] Miro Board - https://miro.com/app/board/o9J_l5ICceA=/?moveToWidget=3074457361739873543&cot=14 - @whitevo 

## Sessions

![2021-07-23 (1)](https://user-images.githubusercontent.com/25156451/126811475-4f10bc3e-9752-4d86-b6ce-9fac5bb32bb5.png)

### 1) Meta-Fund for Challenge Setters and Proposers
Josh Fielding, Robert & Sofih
- F4: Fund6 Challenge Setting - DeFi and Microlending for Africa
https://cardano.ideascale.com/a/dtd/340138-48088
- Town Hall Slides https://docs.google.com/presentation/d/17IOv5yTlr1Mj0YjuBIARazVUNSPG1amYWnqoMYi5huk/edit#slide=id.gb8007c9eb7_0_287

### 2) T&M Problem sensing 3
@FelixfromSwarm 
- Circle Meeting 1 - Toolmaker and Maintainer Circle 
- Tracking https://github.com/Catalyst-Swarm/Catalyst-Circle-Co-ordination/issues/3

### 3) Mini-proposal designing process | Preparing workshop for CA School
@whitevo @stephen-rowan 

Today in Swarm we start the first step towards preparing the workshops for mini-proposals.
Agendas:
1. Why Mini-proposals
2. What should be requirements for mini proposals (besides less than 3000 ADA and 80 hours of building time)
3. How should the process look like (I introduce the way I see it and then we fill holes and rearrange if needed)
https://discord.com/channels/832894680290951179/836887583799246899/868385412282994728

See also MicroTask Catalyst School Workshop - After Town Hall - 28th July 2021 (https://github.com/The-Catalyst-School/The-Catalyst-School-Co-Ordination/issues/12 ) 

### 4) Catalyst Proposal presentation solutions
Maria Carmo
- Brainstorm ideas about a show to present Catalyst proposals

### 5) DAO library
Pete Olivier-Kruger
- Previous session documented here ( https://catalyst-swarm.gitbook.io/catalyst-swarm-genesis/july-2021/swarm-sessions-july-2021#dao-library-hosted-by-pete-oliver-krueger )

### Checklist Documented [here](https://catalyst-swarm.gitbook.io/catalyst-swarm-genesis/governance/saturday-swarm-sessions#checklist) 
- [ ] suggest changes to @stephen-rowan 
- [ ] The host or co-host should assert the main subject over anyone who misdirects the session.
- [ ] Before each session a host should have prepared some content or know what they intend to present.
- [ ] When the session starts the host should ask if the attendees mind being recorded.
- [ ] The host should record the session (if there are no objections).
- [ ] The host should end the recording after the session times out (45 minutes).
- [ ] The host or co-host should take notes of the session.

**Comment by whitevo** [comment]
New file for Swarm events: 
https://docs.google.com/spreadsheets/d/1vnGFw-SipQVJYb0Hz274wTci37srjytF/edit#gid=1824093933
